// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:de907de2-4bf2-4da5-947a-9c5544276cb3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_f5f32zwW9",
    "aws_user_pools_web_client_id": "74hecr23bgmivttvntue8tm4jo"
};


export default awsmobile;
